---

variables:
  DEFAULT_LOCALE: en

.staging:
  variables: &staging
    DOMAIN: staging-new-adblockplus-org-1.uplink.eyeo.it
    FIREBASE_DOMAIN: https://staging.adblockplus.dev/
    PREVIEW_CHANNEL_EXPIRATION: 30d
    STRIPE_PUBLISHABLE_KEY: pk_test_qZJPIgNMdOMferLFulcfPvXO007x2ggldN
    DONATION_SERVER_BASE_URL: https://donation-staging.adblock-org.workers.dev/
    DONATION_SERVER_BASE_URL_V1: https://staging-new-integration-adblockplus-org-1.uplink.eyeo.it/

.production:
  variables: &production
    DOMAIN: new.adblockplus.org
    FIREBASE_DOMAIN: https://www.adblockplus.dev/
    STRIPE_PUBLISHABLE_KEY: pk_live_Nlfxy49RuJeHqF1XOAtUPUXg00fH7wpfXs
    DONATION_SERVER_BASE_URL: https://donation.adblock-org.workers.dev/
    DONATION_SERVER_BASE_URL_V1: https://new-integration.adblockplus.org/

.production0:
  variables: &production0
    DOMAIN: adblockplus.org
  extends:
    ".production"

.common:
  tags:
    - &NODE_IMAGE node:16-alpine
    - &GOOGLE_CLOUD_SDK_IMAGE google/cloud-sdk:409.0.0
    - &BUILD_IMAGE registry.gitlab.com/eyeo/websites/docker/adblockinc-cms-202208.1:latest
    - &TEST_IMAGE registry.gitlab.com/eyeo/websites/docker/python-chromedriver:3.6-xvfb-selenium
    - &BUILD_RUNNER docker
    - &US_RUNNER web-qa-us-proxy-1.uplink.eyeo.it
    - &STAGING_RUNNER eyeo_cms_web_server_staging-new-adblockplus-org-1.uplink.eyeo.it
    - &PRODUCTION_RUNNER0 eyeo_cms_web_server_adblockplus-org-2.adblockplus.org
    - &PRODUCTION_RUNNER1 eyeo_cms_web_server_new-adblockplus-org-1.uplink.eyeo.it
    - &PRODUCTION_RUNNER2 eyeo_cms_web_server_new-adblockplus-org-2.uplink.eyeo.it
    - &PRODUCTION_RUNNER3 eyeo_cms_web_server_new-adblockplus-org-3.uplink.eyeo.it
    - &PRODUCTION_RUNNER4 eyeo_cms_web_server_new-adblockplus-org-4.uplink.eyeo.it
    - &PRODUCTION_RUNNER5 eyeo_cms_web_server_new-adblockplus-org-5.uplink.eyeo.it
    - &PRODUCTION_RUNNER6 eyeo_cms_web_server_new-adblockplus-org-6.uplink.eyeo.it

# https://docs.gitlab.com/ee/ci/yaml/#stages
stages:
  - build_production
  - deploy_production
  - build_staging
  - deploy_staging
  - smoke_tests
  - manually_triggered_tests
  - scheduled_monitoring_tests
  - prebuild_firebase
  - build_firebase
  - deploy_cloud_run
  - deploy_firebase


production_build0:
  variables:
    <<: *production0
  extends:
    "production_build"

deploy_production0:
  variables:
    <<: *production0
  tags:
    - *PRODUCTION_RUNNER0
  extends:
    "deploy_production1"

production_build:
  stage: build_production
  except:
    - schedules
  variables:
    <<: *production
  image: *BUILD_IMAGE
  tags:
    - *BUILD_RUNNER
  before_script:
    - python3 -m pip install -q crudini
  script:
    - crudini --set settings.ini general siteurl https://$DOMAIN
    - python3 -m cms.bin.generate_static_pages $PWD build_production
  artifacts:
    name: $CI_COMMIT_REF_SLUG
    paths:
      - build_production
  only:
    - master

deploy_production1:
  stage: deploy_production
  except:
    - schedules
  variables:
    <<: *production
  tags:
    - *PRODUCTION_RUNNER1
  script:
    - sudo /usr/local/sbin/deploy_eyeo_cms_web_$DOMAIN $CI_PROJECT_DIR/build_production
  environment:
    name: $DOMAIN
    url: http://$DOMAIN
  only:
    - master

deploy_production2:
  tags:
    - *PRODUCTION_RUNNER2
  extends:
    "deploy_production1"

deploy_production3:
  tags:
    - *PRODUCTION_RUNNER3
  extends:
    "deploy_production1"

deploy_production4:
  tags:
    - *PRODUCTION_RUNNER4
  extends:
    "deploy_production1"

deploy_production5:
  tags:
    - *PRODUCTION_RUNNER5
  extends:
    "deploy_production1"

deploy_production6:
  tags:
    - *PRODUCTION_RUNNER6
  extends:
    "deploy_production1"

staging_build:
  stage: build_staging
  except:
    - schedules
  variables:
    <<: *staging
  image: *BUILD_IMAGE
  tags:
    - *BUILD_RUNNER
  before_script:
    - python3 -m pip install -q crudini
  script:
    - crudini --set settings.ini general siteurl http://$CI_COMMIT_REF_SLUG.$DOMAIN
    - python3 -m cms.bin.generate_static_pages $PWD build_staging
  artifacts:
    name: $CI_COMMIT_REF_SLUG
    paths:
      - build_staging

deploy_staging:
  stage: deploy_staging
  except:
    - schedules
  variables:
    <<: *staging
  tags:
    - *STAGING_RUNNER
  dependencies:
    - staging_build
  script:
    - sudo /usr/local/sbin/deploy_eyeo_cms_web_$DOMAIN $CI_PROJECT_DIR/build_staging/
  environment:
    name: staging/$CI_COMMIT_REF_SLUG
    url: http://$CI_COMMIT_REF_SLUG.$DOMAIN

smoke_tests_staging:
  except:
    - schedules
    - master
  stage: smoke_tests
  variables:
    <<: *staging
  image: *TEST_IMAGE
  script:
    - python3 -m pip install tox
    - cd tests/web.adblockplus.org
    - xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" tox -- --landing_page_url=http://$CI_COMMIT_REF_SLUG.$DOMAIN tests/test_DownloadLinks.py

smoke_tests_production:
  except:
    - schedules
  only:
    - master
  stage: smoke_tests
  variables:
    <<: *production
  image: *TEST_IMAGE
  script:
    - python3 -m pip install tox
    - cd tests/web.adblockplus.org
    - xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" tox -- --landing_page_url=https://new.adblockplus.org tests/test_DownloadLinks.py

cookies_settings_tests:
  except:
    - schedules
  stage: manually_triggered_tests
  variables:
    <<: *staging
  image: *TEST_IMAGE
  tags:
    - *US_RUNNER
  script:
    - python3 -m pip install tox
    - cd tests/web.adblockplus.org
    - xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" tox -- --landing_page_url=http://$CI_COMMIT_REF_SLUG.$DOMAIN tests/test_CookiesSettings.py
  when: manual

download_links_tests:
  except:
    - schedules
  stage: manually_triggered_tests
  variables:
    <<: *staging
  image: *TEST_IMAGE
  script:
    - pip install tox
    - cd tests/web.adblockplus.org
    - xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" tox -- --landing_page_url=http://$CI_COMMIT_REF_SLUG.$DOMAIN tests/test_DownloadLinks.py
  when: manual

language_tests:
  except:
    - schedules
  stage: manually_triggered_tests
  variables:
    <<: *staging
  image: *TEST_IMAGE
  script:
    - python3 -m pip install tox
    - cd tests/web.adblockplus.org
    - xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" tox -- --landing_page_url=http://$CI_COMMIT_REF_SLUG.$DOMAIN tests/test_Languages.py
  when: manual

stripe_donate_tests:
  except:
    - schedules
  stage: manually_triggered_tests
  variables:
    <<: *staging
  image: *TEST_IMAGE
  tags:
    - *US_RUNNER
  script:
    - python3 -m pip install tox
    - cd tests/web.adblockplus.org
    - xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" tox -- --landing_page_url=http://$CI_COMMIT_REF_SLUG.$DOMAIN --generic_donation_page=donate tests/test_StripeDonations.py
  when: manual

stripe_installed_tests:
  except:
    - schedules
  stage: manually_triggered_tests
  variables:
    <<: *staging
  image: *TEST_IMAGE
  tags:
    - *US_RUNNER
  script:
    - python3 -m pip install tox
    - cd tests/web.adblockplus.org
    - xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" tox -- --landing_page_url=http://$CI_COMMIT_REF_SLUG.$DOMAIN --generic_donation_page=installed tests/test_StripeDonations.py
  when: manual

stripe_update_tests:
  except:
    - schedules
  stage: manually_triggered_tests
  variables:
    <<: *staging
  image: *TEST_IMAGE
  tags:
    - *US_RUNNER
  script:
    - python3 -m pip install tox
    - cd tests/web.adblockplus.org
    - xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" tox -- --landing_page_url=http://$CI_COMMIT_REF_SLUG.$DOMAIN --generic_donation_page=update tests/test_StripeDonations.py
  when: manual

legacy_redirect_tests:
  except:
    - schedules
  stage: manually_triggered_tests
  variables:
    <<: *staging
  image: *TEST_IMAGE
  tags:
    - *US_RUNNER
  script:
    - python3 -m pip install tox
    - cd tests/web.adblockplus.org
    - xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" tox -- --landing_page_url=http://$CI_COMMIT_REF_SLUG.$DOMAIN tests/test_Redirects.py
  when: manual

lint:
  except:
    - schedules
  stage: manually_triggered_tests
  image: node:latest
  script:
    - npm init -y
    - npm install eslint eslint-config-eyeo --save-dev
    - ./node_modules/.bin/eslint static/js
  when: manual

monitoring_scheduled_tests:
  only:
    - schedules
  stage: scheduled_monitoring_tests
  image: *TEST_IMAGE
  script:
    - python3 -m pip install tox
    - cd tests/web.adblockplus.org
    - xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" tox -- --landing_page_url=http://adblockplus.org/ tests/test_DownloadLinks.py tests/test_MonitorDonationPages.py

pre_review_build:
  stage: prebuild_firebase
  except:
    - master
    - schedules
  image: *NODE_IMAGE
  before_script:
    - npm install -g firebase-tools@11.13.0
    - cp $GCP_SERVICE_ACCOUNT_CREDENTIALS ~/gcp.json
    - export GOOGLE_APPLICATION_CREDENTIALS=~/gcp.json
  script:
    - cd services/firebase
    - firebase use staging
    - node ./prebuild_staging.mjs
  after_script:
    - rm -rf ~/gcp.json
  artifacts:
    reports:
      dotenv: services/firebase/build.env
  environment:
    name: review/$CI_COMMIT_REF_SLUG

build:review:
  stage: build_firebase
  except:
    - master
    - schedules
  variables:
    <<: *staging
  image: *BUILD_IMAGE
  tags:
    - *BUILD_RUNNER
  dependencies:
    - pre_review_build
  before_script:
    - python3 -m pip install -q crudini
  script:
    - crudini --set settings.ini general siteurl "$REVIEW_URL"
    - python3 -m cms.bin.generate_static_pages $PWD services/firebase/public
    - python services/firebase/utils/html_extender.py services/firebase/public
    # copy contents of default locale to base of public root (for firebase), 
    # this addresses getting canonical page if no language translation available
    - cp -a services/firebase/public/$DEFAULT_LOCALE/. services/firebase/public/.
  artifacts:
    name: $CI_COMMIT_REF_SLUG
    paths:
      - services/firebase/public

build:review:staging:
  stage: build_firebase
  except:
    - schedules
  variables:
    <<: *staging
  image: *BUILD_IMAGE
  tags:
    - *BUILD_RUNNER
  before_script:
    - python3 -m pip install -q crudini
  script:
    - crudini --set settings.ini general siteurl "$FIREBASE_DOMAIN"
    - python3 -m cms.bin.generate_static_pages $PWD services/firebase/public
    - python services/firebase/utils/html_extender.py services/firebase/public
    # copy contents of default locale to base of public root (for firebase), 
    # this addresses getting canonical page if no language translation available
    - cp -a services/firebase/public/$DEFAULT_LOCALE/. services/firebase/public/.
  artifacts:
    name: $CI_COMMIT_REF_SLUG
    paths:
      - services/firebase/public
  only:
    - master

build:production:
  stage: build_firebase
  except:
    - schedules
  variables:
    <<: *production
  image: *BUILD_IMAGE
  tags:
    - *BUILD_RUNNER
  before_script:
    - python3 -m pip install -q crudini
  script:
    - crudini --set settings.ini general siteurl "$FIREBASE_DOMAIN"
    - python3 -m cms.bin.generate_static_pages $PWD services/firebase/public
    - python services/firebase/utils/html_extender.py services/firebase/public
    # copy contents of default locale to base of public root (for firebase), 
    # this addresses getting canonical page if no language translation available
    - cp -a services/firebase/public/$DEFAULT_LOCALE/. services/firebase/public/.
  artifacts:
    name: $CI_COMMIT_REF_SLUG
    paths:
      - services/firebase/public
  only:
    - master

deploy_cloud_run:review:
  stage: deploy_cloud_run
  except:
    - master
    - schedules
  image: *GOOGLE_CLOUD_SDK_IMAGE
  before_script:
    - gcloud auth activate-service-account --key-file $GCP_SERVICE_ACCOUNT_CREDENTIALS
    - gcloud config set project $GCP_PROJECT_ID
  script:
    - cd services/cloudrun
    - gcloud builds submit --tag gcr.io/$GCP_PROJECT_ID/$CI_COMMIT_REF_SLUG
    - gcloud run deploy $CI_COMMIT_REF_SLUG --image gcr.io/$GCP_PROJECT_ID/$CI_COMMIT_REF_SLUG:latest --region europe-west1 --allow-unauthenticated
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    on_stop: teardown_cloud_run:review

teardown_cloud_run:review:
  stage: deploy_cloud_run
  except:
    - master
    - schedules
  image: *GOOGLE_CLOUD_SDK_IMAGE
  before_script:
    - gcloud auth activate-service-account --key-file $GCP_SERVICE_ACCOUNT_CREDENTIALS
    - gcloud config set project $GCP_PROJECT_ID
  script:
    - gcloud run services delete $CI_COMMIT_REF_SLUG --region europe-west1 --quiet
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop
  when: manual

deploy_cloud_run:review:staging:
  stage: deploy_cloud_run
  except:
    - schedules
  image: *GOOGLE_CLOUD_SDK_IMAGE
  before_script:
    - gcloud auth activate-service-account --key-file $GCP_SERVICE_ACCOUNT_CREDENTIALS
    - gcloud config set project $GCP_PROJECT_ID
  script:
    - cd services/cloudrun
    - gcloud builds submit --tag gcr.io/$GCP_PROJECT_ID/$CI_COMMIT_REF_SLUG
    - gcloud run deploy $CI_COMMIT_REF_SLUG --image gcr.io/$GCP_PROJECT_ID/$CI_COMMIT_REF_SLUG:latest --region europe-west1 --allow-unauthenticated
  environment:
    name: review/staging/$CI_COMMIT_REF_SLUG
  only:
    - master

deploy_cloud_run:production:
  stage: deploy_cloud_run
  except:
    - schedules
  image: *GOOGLE_CLOUD_SDK_IMAGE
  before_script:
    - gcloud auth activate-service-account --key-file $GCP_SERVICE_ACCOUNT_CREDENTIALS
    - gcloud config set project $GCP_PROJECT_ID
  script:
    - cd services/cloudrun
    - gcloud builds submit --tag gcr.io/$GCP_PROJECT_ID/$CI_COMMIT_REF_SLUG
    - gcloud run deploy $CI_COMMIT_REF_SLUG --image gcr.io/$GCP_PROJECT_ID/$CI_COMMIT_REF_SLUG:latest --region europe-west1 --allow-unauthenticated
  environment:
    name: production/$CI_COMMIT_REF_SLUG
  only:
    - master

deploy_firebase_hosting:review:
  stage: deploy_firebase
  except:
    - master
    - schedules
  image: *NODE_IMAGE
  variables:
    <<: *staging
  dependencies:
    - pre_review_build
    - build:review
  before_script:
    - npm install -g firebase-tools@11.13.0
    - npm install commander@"~9.4.0"
    - npm install json5@"~2.2.1"
    - cp $GCP_SERVICE_ACCOUNT_CREDENTIALS ~/gcp.json
    - export GOOGLE_APPLICATION_CREDENTIALS=~/gcp.json
  script:
    - npm run rename-service-ids -- --input ./services/firebase/firebase.json --name $CI_COMMIT_REF_SLUG
    - cd services/firebase
    - firebase use staging
    - firebase hosting:channel:deploy $CI_COMMIT_REF_SLUG --expires $PREVIEW_CHANNEL_EXPIRATION
  after_script:
    - rm -rf ~/gcp.json
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: $REVIEW_URL
    on_stop: teardown_firebase_hosting:review

teardown_firebase_hosting:review:
  stage: deploy_firebase
  except:
    - master
    - schedules
  image: *NODE_IMAGE
  before_script:
    - npm install -g firebase-tools@11.13.0
    - cp $GCP_SERVICE_ACCOUNT_CREDENTIALS ~/gcp.json
    - export GOOGLE_APPLICATION_CREDENTIALS=~/gcp.json
  script:
    - cd services/firebase
    - firebase use staging
    - firebase hosting:channel:delete $CI_COMMIT_REF_SLUG -f
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop
  when: manual

deploy_firebase_hosting:review:staging:
  stage: deploy_firebase
  except:
    - schedules
  image:
    *NODE_IMAGE
  variables:
    <<: *staging
  dependencies:
    - build:review:staging
  before_script:
    - npm install -g firebase-tools@11.13.0
    - npm install commander@"~9.4.0"
    - npm install json5@"~2.2.1"
    - cp $GCP_SERVICE_ACCOUNT_CREDENTIALS ~/gcp.json
    - export GOOGLE_APPLICATION_CREDENTIALS=~/gcp.json
  script:
    - npm run rename-service-ids -- --input ./services/firebase/firebase.json --name $CI_COMMIT_REF_SLUG
    - cd services/firebase
    - firebase use staging
    - firebase deploy --only hosting
  after_script:
    - rm -rf ~/gcp.json
  environment:
    name: review/staging/$CI_COMMIT_REF_SLUG
    url: $FIREBASE_DOMAIN
  only:
    - master

deploy_firebase_hosting:production:
  stage: deploy_firebase
  except:
    - schedules
  image: *NODE_IMAGE
  variables:
    <<: *production
  dependencies:
    - build:production
  before_script:
    - npm install -g firebase-tools@11.13.0
    - npm install commander@"~9.4.0"
    - npm install json5@"~2.2.1"
    - cp $GCP_SERVICE_ACCOUNT_CREDENTIALS ~/gcp.json
    - export GOOGLE_APPLICATION_CREDENTIALS=~/gcp.json
  script:
    - npm run rename-service-ids -- --input ./services/firebase/firebase.json --name $CI_COMMIT_REF_SLUG
    - cd services/firebase
    - firebase use production
    - firebase deploy --only hosting
  after_script:
    - rm -rf ~/gcp.json
  environment:
    name: production/$CI_COMMIT_REF_SLUG
    url: $FIREBASE_DOMAIN
  only:
    - master
