image: python:2

before_script:
  - apt-get update -qq
  - apt-get install -y -qq rpl rename
  - pip install -q Markdown Jinja2 lxml crudini
  - git clone -b import_export_csv --single-branch https://gitlab.com/eyeo/websites/cms.git $HOME/cms
  - git clone -b master --single-branch https://github.com/adblockplus/sitescripts $HOME/sitescripts
  - export PYTHONPATH="$HOME/cms:$HOME/sitescripts:$PYTHONPATH"

pages:
  stage: deploy
  script:
    - SITEURL="https://${CI_PROJECT_NAMESPACE}.gitlab.io/${CI_PROJECT_NAME}"
    - crudini --set settings.ini general siteurl "${SITEURL}"
    - python -m cms.bin.generate_static_pages --version public . public
    - python -m cms.bin.export_csv . > public/latest.csv
    - SITEURL=$(crudini --get settings.ini general siteurl)
    - rpl -Rq 'src="/' "src=\"${SITEURL}" public/
    - rpl -Rq 'srcset="/' "srcset=\"${SITEURL}" public/
    - rpl -Rq 'href="/' "href=\"${SITEURL}" public/
    - rpl -Rq 'url(/' "url(${SITEURL}" public/
    - rpl -Rq 'url("/' "url(\"${SITEURL}" public/
    - rename 's/index/index.html/' public/**/index
  artifacts:
    paths:
      - public
