export default {
  currencySelect: "appeal-form-header__select",
  onceAmount1: "appeal-form-amount__radio--once-0",
  onceAmount2: "appeal-form-amount__radio--once-1",
  onceAmount3: "appeal-form-amount__radio--once-2",
  onceAmount4: "appeal-form-amount__radio--once-3",
  onceAmount5: "appeal-form-amount__radio--once-4",
  onceCustomRadio: "appeal-form-amount__radio--once-5",
  onceCustomInput: "appeal-form-amount__input--once",
  monthlyAmount1: "appeal-form-amount__radio--monthly-0",
  monthlyAmount2: "appeal-form-amount__radio--monthly-1",
  monthlyAmount3: "appeal-form-amount__radio--monthly-2",
  monthlyAmount4: "appeal-form-amount__radio--monthly-3",
  monthlyAmount5: "appeal-form-amount__radio--monthly-4",
  monthlyCustomRadio: "appeal-form-amount__radio--monthly-5",
  monthlyCustomInput: "appeal-form-amount__input--monthly",
  yearlyAmount1: "appeal-form-amount__radio--yearly-0",
  yearlyAmount2: "appeal-form-amount__radio--yearly-1",
  yearlyAmount3: "appeal-form-amount__radio--yearly-2",
  yearlyAmount4: "appeal-form-amount__radio--yearly-3",
  yearlyAmount5: "appeal-form-amount__radio--yearly-4",
  yearlyCustomRadio: "appeal-form-amount__radio--yearly-5",
  yearlyCustomInput: "appeal-form-amount__input--yearly",
  errorMessage: "appeal-form__error",
  checkoutButton: "appeal-form-checkout__submit",
};