subscriptions = {
    'order': [
        'EasyList',
        'ABPindo',
        'ABPVN List',
        'Bulgarian list',
        "Dandelion Sprout's Nordic Filters",
        'EasyList China',
        'EasyList Czech and Slovak',
        'EasyList Dutch',
        'EasyList Germany',
        'EasyList Hebrew',
        'EasyList Italy',
        'EasyList Lithuania',
        'EasyList Polish',
        'EasyList Portuguese',
        'EasyList Spanish',
        'Global Filters',
        'hufilter',
        'IndianList',
        'Japanese Filters',
        'KoreanList',
        'Latvian List',
        'Liste AR',
        'Liste FR',
        'ROList',
        'RU AdList',
        'Turkish Filters',
        '280blocker for japanese mobile site',
        'ABP Japanese Filters',
        'AdBlockFarsi',
        "CJX's Annoyance List",
        'Colombian filters by yecarrillo',
        'Eesti saitidele kohandatud filter',
        'Estonian filters by Gurud.ee',
        'Icelandic ABP List',
        "Peter Lowe's list",
        'Raajje Adlist',
         'Tiswagos Liri AdBlockList',
        'void.gr',
        'Xfiles',
        'YousList',
        'Adblock Warning Removal List',
        'ABP filters',
        "I don't care about cookies",
        'EasyList Cookie List',
        'Spam404',
        "Fanboy's Notifications Blocking List",
        'CPBL Filters for Adblock Plus',
        'NoCoin',
        'EasyPrivacy',
        "Fanboy's Social Blocking List",
        ],
    '280blocker for japanese mobile site': {
        'blog': None,
        'changelog': None,
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': 'https://280blocker.net/',
        'maintainer': '280',
        'policy': None,
        'specialization': '\u65e5\u672c\u8a9e',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': 'ads',
        'variants': [['280blocker for japanese mobile site',
                     'https://280blocker.net/files/280blocker_adblock.txt'
                     , False]],
        },
    'ABP Japanese Filters': {
        'blog': 'http://d.hatena.ne.jp/k2jp/',
        'changelog': 'https://github.com/k2jp/abp-japanese-filters/commits/master/abpjf.txt',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://groups.google.com/group/adblock-plus-japanese-filter',
        'homepage': 'https://github.com/k2jp/abp-japanese-filters/',
        'maintainer': 'k2japan',
        'policy': None,
        'specialization': '\u65e5\u672c\u8a9e',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': 'ads',
        'variants': [['ABP Japanese Filters', 'https://bit.ly/11QrCfx'
                     , False]],
        },
    'ABP filters': {
        'blog': None,
        'changelog': 'https://github.com/abp-filters/abp-filters-anti-cv/commits/master',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://github.com/abp-filters/abp-filters-anti-cv/issues',
        'homepage': 'https://github.com/abp-filters/abp-filters-anti-cv',
        'maintainer': 'eyeo GmbH',
        'policy': None,
        'specialization': 'Adblock Plus (ABP) filter list to fight "circumvention ads"',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': 'circumvention',
        'variants': [['ABP filters',
                     'https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt'
                     , False]],
        },
    'ABPVN List': {
        'blog': None,
        'changelog': 'https://github.com/abpvn/abpvn/commits/master/filter/abpvn.txt',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://voz.vn/t/abpvn-chan-quang-cao-cho-nguoi-viet.25778/',
        'homepage': 'https://abpvn.com/',
        'maintainer': 'Ho\xe0ng Rio',
        'policy': None,
        'specialization': 'Ti\u1ebfng Vi\u1ec7t',
        'supplemented': [],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'ads',
        'variants': [['ABPVN List+EasyList',
                     'https://easylist-downloads.adblockplus.org/abpvn+easylist.txt'
                     , True], ['ABPVN List',
                     'https://raw.githubusercontent.com/abpvn/abpvn/master/filter/abpvn.txt'
                     , False]],
        },
    'ABPindo': {
        'blog': None,
        'changelog': None,
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://forums.lanik.us/viewforum.php?f=94',
        'homepage': 'https://github.com/ABPindo/indonesianadblockrules',
        'maintainer': 'heradhis',
        'policy': None,
        'specialization': 'Bahasa Indonesia, Melayu',
        'supplemented': [],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'ads',
        'variants': [['ABPindo+EasyList',
                     'https://easylist-downloads.adblockplus.org/abpindo+easylist.txt'
                     , True], ['ABPindo',
                     'https://raw.githubusercontent.com/ABPindo/indonesianadblockrules/master/subscriptions/abpindo.txt'
                     , False]],
        },
    'AdBlockFarsi': {
        'blog': None,
        'changelog': 'https://github.com/SlashArash/adblockfa/commits/master/adblockfa.txt',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://github.com/SlashArash/adblockfa/issues',
        'homepage': 'https://github.com/SlashArash/adblockfa',
        'maintainer': 'Arash Kadkhodaei',
        'policy': None,
        'specialization': '\u0641\u0627\u0631\u0633\u06cc',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': 'ads',
        'variants': [['AdBlockFarsi',
                     'https://raw.githubusercontent.com/SlashArash/adblockfa/master/adblockfa.txt'
                     , False]],
        },
    'Adblock Warning Removal List': {
        'blog': None,
        'changelog': None,
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': 'https://easylist.to/',
        'maintainer': 'authors of recommended filter lists',
        'policy': None,
        'specialization': 'removes anti-adblock warnings and other obtrusive messages',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': 'anti-adblock',
        'variants': [['Adblock Warning Removal List',
                     'https://easylist-downloads.adblockplus.org/antiadblockfilters.txt'
                     , False]],
        },
    'Bulgarian list': {
        'blog': None,
        'changelog': None,
        'contact': 'https://stanev.org/abp/?SendFilters',
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': 'https://stanev.org/abp/',
        'maintainer': '\u0410\u043b\u0435\u043a\u0441\u0430\u043d\u0434\u044a\u0440 \u0421\u0442\u0430\u043d\u0435\u0432',
        'policy': None,
        'specialization': '\u0431\u044a\u043b\u0433\u0430\u0440\u0441\u043a\u0438',
        'supplemented': [],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'ads',
        'variants': [['Bulgarian list+EasyList',
                     'https://easylist-downloads.adblockplus.org/bulgarian_list+easylist.txt'
                     , True], ['Bulgarian list',
                     'https://stanev.org/abp/adblock_bg.txt', False]],
        },
    "CJX's Annoyance List": {
        'blog': None,
        'changelog': None,
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': 'https://github.com/cjx82630/cjxlist',
        'maintainer': 'John',
        'policy': None,
        'specialization': 'removes self-promotion and privacy protection, \u4e2d\u6587',
        'supplemented': [],
        'supplements': ['EasyList China'],
        'supplementsType': ['ads'],
        'type': 'ads',
        'variants': [["CJX's Annoyance List",
                     'https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt'
                     , False]],
        },
    'CPBL Filters for Adblock Plus': {
        'blog': None,
        'changelog': 'https://github.com/bongochong/CombinedPrivacyBlockLists/commits/master/cpbl-abp-list.txt',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://git.io/JTTL0',
        'homepage': 'https://git.io/JTTLB',
        'maintainer': 'Bongochong',
        'policy': None,
        'specialization': 'removes ads, trackers/telemetry, malware and scams',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': 'other',
        'variants': [['CPBL Filters for Adblock Plus',
                     'https://raw.githubusercontent.com/bongochong/CombinedPrivacyBlockLists/master/cpbl-abp-list.txt'
                     , False]],
        },
    'Colombian filters by yecarrillo': {
        'blog': None,
        'changelog': 'https://github.com/yecarrillo/adblock-colombia/commits/master/adblock_co.txt',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://www.laneros.com/temas/adblockers-y-lista-de-filtros-de-publicidad-para-colombia.230398/',
        'homepage': 'https://github.com/yecarrillo/adblock-colombia',
        'maintainer': 'Yezid Carrillo',
        'policy': None,
        'specialization': 'espa\xf1ol',
        'supplemented': [],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'ads',
        'variants': [['Colombian filters by yecarrillo',
                     'https://raw.githubusercontent.com/yecarrillo/adblock-colombia/master/adblock_co.txt'
                     , False]],
        },
    "Dandelion Sprout's Nordic Filters": {
        'blog': None,
        'changelog': 'https://github.com/DandelionSprout/adfilt/commits/master/NorwegianExperimentalList%20alternate%20versions/NordicFiltersABP-Inclusion.txt',
        'contact': 'https://github.com/DandelionSprout/adfilt/issues',
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': 'https://github.com/DandelionSprout/adfilt',
        'maintainer': 'Imre Kristoffer Eilertsen',
        'policy': None,
        'specialization': 'norsk, norsk, norsk, dansk, \xedslenska, f\xf8royskt, kalaallisut, suomi',
        'supplemented': [],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'ads',
        'variants': [["Dandelion Sprout's Nordic Filters+EasyList",
                     'https://easylist-downloads.adblockplus.org/dandelion_sprouts_nordic_filters+easylist.txt'
                     , True], ["Dandelion Sprout's Nordic Filters",
                     'https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/NordicFiltersABP-Inclusion.txt'
                     , False]],
        },
    'EasyList': {
        'blog': 'https://easylist.to/category/articles.html',
        'changelog': 'https://github.com/easylist/easylist/commits/master',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://forums.lanik.us/',
        'homepage': 'https://easylist.to/',
        'maintainer': 'fanboy, MonztA, Khrin, Yuki2718, PiQuark6046',
        'policy': 'https://easylist.to/pages/policy.html',
        'specialization': 'English',
        'supplemented': [
            'ABPindo',
            'ABPVN List',
            'Bulgarian list',
            "Dandelion Sprout's Nordic Filters",
            'EasyList China',
            'EasyList Czech and Slovak',
            'EasyList Dutch',
            'EasyList Germany',
            'EasyList Hebrew',
            'EasyList Italy',
            'EasyList Lithuania',
            'EasyList Polish',
            'EasyList Portuguese',
            'EasyList Spanish',
            'Global Filters',
            'hufilter',
            'IndianList',
            'Japanese Filters',
            'KoreanList',
            'Latvian List',
            'Liste FR',
            'ROList',
            'RU AdList',
            'Turkish Filters',
            'Colombian filters by yecarrillo',
            'Icelandic ABP List',
            'void.gr',
            ],
        'supplements': [],
        'supplementsType': [],
        'type': 'ads',
        'variants': [['EasyList',
                     'https://easylist-downloads.adblockplus.org/easylist.txt'
                     , False]],
        },
    'EasyList China': {
        'blog': None,
        'changelog': 'https://github.com/easylist/easylistchina/commits/master',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': 'https://github.com/easylist/easylistchina',
        'maintainer': 'John',
        'policy': None,
        'specialization': '\u4e2d\u6587',
        'supplemented': ["CJX's Annoyance List"],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'ads',
        'variants': [['EasyList China+EasyList',
                     'https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt'
                     , True], ['EasyList China',
                     'https://easylist-downloads.adblockplus.org/easylistchina.txt'
                     , False]],
        },
    'EasyList Cookie List': {
        'blog': None,
        'changelog': 'https://github.com/easylist/easylist/commits/master/easylist_cookie',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://forums.lanik.us/',
        'homepage': 'https://easylist.to/',
        'maintainer': 'fanboy, Khrin, MonztA',
        'policy': None,
        'specialization': 'cookies banners, GDPR overlay windows and other privacy-related notices',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': 'cookies',
        'variants': [['EasyList Cookie List',
                     'https://easylist-downloads.adblockplus.org/easylist-cookie.txt'
                     , False]],
        },
    'EasyList Czech and Slovak': {
        'blog': None,
        'changelog': 'https://github.com/tomasko126/easylistczechandslovak/commits/master/filters.txt',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://easylist-czech-and-slovak.tenderapp.com/',
        'homepage': 'https://adblock.sk/',
        'maintainer': 'tomasko126',
        'policy': None,
        'specialization': '\u010de\u0161tina, sloven\u010dina',
        'supplemented': [],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'ads',
        'variants': [['EasyList Czech and Slovak+EasyList',
                     'https://easylist-downloads.adblockplus.org/easylistczechslovak+easylist.txt'
                     , True], ['EasyList Czech and Slovak',
                     'https://raw.github.com/tomasko126/easylistczechandslovak/master/filters.txt'
                     , False]],
        },
    'EasyList Dutch': {
        'blog': None,
        'changelog': 'https://github.com/easylist/easylistdutch/commits/master',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://forums.lanik.us/viewforum.php?f=100',
        'homepage': 'https://easylist.to/',
        'maintainer': 'Khrin',
        'policy': None,
        'specialization': 'Nederlands',
        'supplemented': [],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'ads',
        'variants': [['EasyList Dutch+EasyList',
                     'https://easylist-downloads.adblockplus.org/easylistdutch+easylist.txt'
                     , True], ['EasyList Dutch',
                     'https://easylist-downloads.adblockplus.org/easylistdutch.txt'
                     , False]],
        },
    'EasyList Germany': {
        'blog': None,
        'changelog': 'https://github.com/easylist/easylistgermany/commits/master',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://forums.lanik.us/viewforum.php?f=90',
        'homepage': 'https://easylist.to/',
        'maintainer': 'MonztA, Khrin',
        'policy': 'https://easylist.to/pages/policy.html',
        'specialization': 'Deutsch',
        'supplemented': [],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'ads',
        'variants': [['EasyList Germany+EasyList',
                     'https://easylist-downloads.adblockplus.org/easylistgermany+easylist.txt'
                     , True], ['EasyList Germany',
                     'https://easylist-downloads.adblockplus.org/easylistgermany.txt'
                     , False]],
        },
    'EasyList Hebrew': {
        'blog': None,
        'changelog': 'https://github.com/easylist/EasyListHebrew/commits/master/EasyListHebrew.txt',
        'contact': 'https://github.com/easylist/EasyListHebrew/wiki/%D7%93%D7%99%D7%95%D7%95%D7%97-%D7%A2%D7%9C-%D7%A4%D7%A8%D7%A1%D7%95%D7%9E%D7%95%D7%AA-%D7%95%D7%91%D7%A2%D7%99%D7%95%D7%AA-%7C-Reporting-on-ads-and-problems',
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': 'https://github.com/easylist/EasyListHebrew',
        'maintainer': 'BsT',
        'policy': None,
        'specialization': '\u05e2\u05d1\u05e8\u05d9\u05ea',
        'supplemented': [],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'ads',
        'variants': [['EasyList Hebrew+EasyList',
                     'https://easylist-downloads.adblockplus.org/israellist+easylist.txt'
                     , True], ['EasyList Hebrew',
                     'https://raw.githubusercontent.com/easylist/EasyListHebrew/master/EasyListHebrew.txt'
                     , False]],
        },
    'EasyList Italy': {
        'blog': None,
        'changelog': 'https://github.com/easylist/easylistitaly/commits/master',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://forums.lanik.us/viewforum.php?f=96',
        'homepage': 'https://easylist.to/',
        'maintainer': 'Khrin',
        'policy': 'https://easylist.to/pages/policy.html',
        'specialization': 'italiano',
        'supplemented': [],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'ads',
        'variants': [['EasyList Italy+EasyList',
                     'https://easylist-downloads.adblockplus.org/easylistitaly+easylist.txt'
                     , True], ['EasyList Italy',
                     'https://easylist-downloads.adblockplus.org/easylistitaly.txt'
                     , False]],
        },
    'EasyList Lithuania': {
        'blog': None,
        'changelog': 'https://github.com/EasyList-Lithuania/easylist_lithuania/commits/master/easylistlithuania.txt',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://forums.lanik.us/viewforum.php?f=101',
        'homepage': 'https://github.com/EasyList-Lithuania/easylist_lithuania',
        'maintainer': 'Imre Kristoffer Eilertsen',
        'policy': None,
        'specialization': 'lietuvi\u0173 kalba',
        'supplemented': [],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'ads',
        'variants': [['EasyList Lithuania+EasyList',
                     'https://easylist-downloads.adblockplus.org/easylistlithuania+easylist.txt'
                     , True], ['EasyList Lithuania',
                     'https://raw.githubusercontent.com/EasyList-Lithuania/easylist_lithuania/master/easylistlithuania.txt'
                     , False]],
        },
    'EasyList Polish': {
        'blog': None,
        'changelog': None,
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://forums.lanik.us/viewforum.php?f=107',
        'homepage': 'https://easylist.to/',
        'maintainer': 'bartoszsobkowiak, mateuszfranckiewicz',
        'policy': 'https://easylist.to/pages/policy.html',
        'specialization': 'polski',
        'supplemented': [],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'ads',
        'variants': [['EasyList Polish+EasyList',
                     'https://easylist-downloads.adblockplus.org/easylistpolish+easylist.txt'
                     , True], ['EasyList Polish',
                     'https://easylist-downloads.adblockplus.org/easylistpolish.txt'
                     , False]],
        },
    'EasyList Portuguese': {
        'blog': None,
        'changelog': 'https://github.com/easylist/easylistportuguese/commits/master',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://forums.lanik.us/viewforum.php?f=109',
        'homepage': 'https://easylist.to/',
        'maintainer': 'Felippe Santos',
        'policy': 'https://easylist.to/pages/policy.html',
        'specialization': 'portugu\xeas',
        'supplemented': [],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'ads',
        'variants': [['EasyList Portuguese+EasyList',
                     'https://easylist-downloads.adblockplus.org/easylistportuguese+easylist.txt'
                     , True], ['EasyList Portuguese',
                     'https://easylist-downloads.adblockplus.org/easylistportuguese.txt'
                     , False]],
        },
    'EasyList Spanish': {
        'blog': None,
        'changelog': 'https://github.com/easylist/easylistspanish/commits/master',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://forums.lanik.us/viewforum.php?f=103',
        'homepage': 'https://easylist.to/',
        'maintainer': 'Felippe Santos',
        'policy': 'https://easylist.to/pages/policy.html',
        'specialization': 'espa\xf1ol',
        'supplemented': [],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'ads',
        'variants': [['EasyList Spanish+EasyList',
                     'https://easylist-downloads.adblockplus.org/easylistspanish+easylist.txt'
                     , True], ['EasyList Spanish',
                     'https://easylist-downloads.adblockplus.org/easylistspanish.txt'
                     , False]],
        },
    'EasyPrivacy': {
        'blog': 'https://easylist.to/category/articles.html',
        'changelog': 'https://github.com/easylist/easylist/commits/master/easyprivacy',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://forums.lanik.us/',
        'homepage': 'https://easylist.to/',
        'maintainer': 'fanboy, MonztA, Khrin',
        'policy': 'https://easylist.to/pages/policy.html',
        'specialization': 'privacy protection',
        'supplemented': [],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'privacy',
        'variants': [['EasyPrivacy',
                     'https://easylist-downloads.adblockplus.org/easyprivacy.txt'
                     , False], ['EasyPrivacy+EasyList',
                     'https://easylist-downloads.adblockplus.org/easyprivacy+easylist.txt'
                     , True]],
        },
    'Eesti saitidele kohandatud filter': {
        'blog': None,
        'changelog': None,
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': 'https://adblock.ee/',
        'maintainer': 'Sander Lepik',
        'policy': None,
        'specialization': 'Eesti keel',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': 'ads',
        'variants': [['Eesti saitidele kohandatud filter',
                     'https://adblock.ee/list.php', False]],
        },
    'Estonian filters by Gurud.ee': {
        'blog': None,
        'changelog': None,
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': 'https://gurud.ee/',
        'maintainer': 'Janno Lamus',
        'policy': None,
        'specialization': 'Eesti keel',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': 'ads',
        'variants': [['Estonian filters by Gurud.ee',
                     'https://gurud.ee/ab.txt', False]],
        },
    "Fanboy's Notifications Blocking List": {
        'blog': None,
        'changelog': 'https://github.com/easylist/easylist/commits/master/fanboy-addon',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://forums.lanik.us/',
        'homepage': 'https://easylist.to/',
        'maintainer': 'fanboy',
        'policy': None,
        'specialization': "removes website notification popups (included in Fanboy's Annoyances)",
        'supplemented': [],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'notifications',
        'variants': [["Fanboy's Notifications Blocking List",
                     'https://easylist-downloads.adblockplus.org/fanboy-notifications.txt'
                     , False]],
        },
    "Fanboy's Social Blocking List": {
        'blog': None,
        'changelog': 'https://github.com/easylist/easylist/commits/master/fanboy-addon',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://forums.lanik.us/',
        'homepage': 'https://easylist.to/',
        'maintainer': 'fanboy, Khrin, MonztA',
        'policy': None,
        'specialization': 'removes social media integration',
        'supplemented': [],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'social',
        'variants': [["Fanboy's Social Blocking List",
                     'https://easylist-downloads.adblockplus.org/fanboy-social.txt'
                     , False]],
        },
    'Global Filters': {
        'blog': None,
        'changelog': 'https://gitlab.com/eyeo/filterlists/globalfilters/-/commits/main/',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://gitlab.com/eyeo/filterlists/globalfilters/-/issues',
        'homepage': 'https://gitlab.com/eyeo/filterlists/globalfilters',
        'maintainer': 'eyeo GmbH',
        'policy': None,
        'specialization': '\u0e20\u0e32\u0e29\u0e32\u0e44\u0e17\u0e22, \u0395\u03bb\u03bb\u03b7\u03bd\u03b9\u03ba\u03ae, \u0053\u006c\u006f\u0076\u0065\u006e\u0161\u010d\u0069\u006e\u0061, \u0048\u0072\u0076\u0061\u0074\u0073\u006b\u0069, \u0421\u0440\u043f\u0441\u043a\u0438, \u0042\u006f\u0073\u0061\u006e\u0073\u006b\u0069',
        'supplemented': [],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'ads',
        'variants': [['Global Filters+EasyList',
                     'https://easylist-downloads.adblockplus.org/global-filters+easylist.txt'
                     , True], ['Global Filters',
                     'https://easylist-downloads.adblockplus.org/global-filters.txt'
                     , False]],
        },
    "I don't care about cookies": {
        'blog': None,
        'changelog': None,
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': 'https://www.i-dont-care-about-cookies.eu/',
        'maintainer': 'Gen Digital Inc.',
        'policy': None,
        'specialization': 'filters obtrusive EU cookie law notices',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': 'cookies',
        'variants': [["I don't care about cookies",
                     'https://easylist-downloads.adblockplus.org/i_dont_care_about_cookies.txt'
                     , False]],
        },
    'Icelandic ABP List': {
        'blog': None,
        'changelog': None,
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': 'https://adblock.gardar.net/',
        'maintainer': 'Gar\xf0ar',
        'policy': None,
        'specialization': '\xedslenska',
        'supplemented': [],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'ads',
        'variants': [['Icelandic ABP List',
                     'https://adblock.gardar.net/is.abp.txt', False]],
        },
    'IndianList': {
        'blog': None,
        'changelog': 'https://github.com/mediumkreation/IndianList/commits/master/IndianList',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://forums.lanik.us/viewforum.php?f=110',
        'homepage': 'https://easylist.to/',
        'maintainer': 'mediumkreation',
        'policy': 'https://easylist.to/pages/policy.html',
        'specialization': '\u09ac\u09be\u0982\u09b2\u09be (\u09ad\u09be\u09b0\u09a4), \u0a97\u0ac1\u0a9c\u0ab0\u0abe\u0aa4\u0ac0 (\u0aad\u0abe\u0ab0\u0aa4), \u092d\u093e\u0930\u0924\u0940\u092f, \u0a2a\u0a70\u0a1c\u0a3e\u0a2c\u0a40 (\u0a2d\u0a3e\u0a30\u0a24), \u0985\u09b8\u09ae\u09c0\u09af\u09bc\u09be, \u092e\u0930\u093e\u0920\u0940, \u0d2e\u0d32\u0d2f\u0d3e\u0d33\u0d02, \u0c24\u0c46\u0c32\u0c41\u0c17\u0c41, \u0c95\u0ca8\u0ccd\u0ca8\u0ca1, \u0b13\u0b21\u0b3c\u0b3f\u0b06, \u0928\u0947\u092a\u093e\u0932\u0940, \u0dc3\u0dd2\u0d82\u0dc4\u0dbd',
        'supplemented': [],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'ads',
        'variants': [['IndianList+EasyList',
                     'https://easylist-downloads.adblockplus.org/indianlist+easylist.txt'
                     , True], ['IndianList',
                     'https://easylist-downloads.adblockplus.org/indianlist.txt'
                     , False]],
        },
    'Japanese Filters': {
        'blog': None,
        'changelog': 'https://gitlab.com/eyeo/filterlists/japanesefilters/-/commits/main/',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://gitlab.com/eyeo/filterlists/japanesefilters/-/issues',
        'homepage': 'https://gitlab.com/eyeo/filterlists/japanesefilters',
        'maintainer': 'eyeo GmbH',
        'policy': None,
        'specialization': '\u65e5\u672c\u8a9e',
        'supplemented': [],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'ads',
        'variants': [['Japanese Filters+EasyList',
                     'https://easylist-downloads.adblockplus.org/japanese-filters+easylist.txt'
                     , True], ['Japanese Filters',
                     'https://easylist-downloads.adblockplus.org/japanese-filters.txt'
                     , False]],
        },
    'KoreanList': {
        'blog': None,
        'changelog': 'https://github.com/easylist/KoreanList/commits/master/KoreanList',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://forums.lanik.us/viewforum.php?f=111',
        'homepage': 'https://easylist.to/',
        'maintainer': 'Mark Choi',
        'policy': 'https://easylist.to/pages/policy.html',
        'specialization': '\ud55c\uad6d\uc5b4',
        'supplemented': [],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'ads',
        'variants': [['KoreanList+EasyList',
                     'https://easylist-downloads.adblockplus.org/koreanlist+easylist.txt'
                     , True], ['KoreanList',
                     'https://easylist-downloads.adblockplus.org/koreanlist.txt'
                     , False]],
        },
    'Latvian List': {
        'blog': None,
        'changelog': 'https://github.com/Latvian-List/adblock-latvian/commits/master',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://forums.lanik.us/viewforum.php?f=99-latvian-list',
        'homepage': 'https://forums.lanik.us/viewforum.php?f=99-latvian-list',
        'maintainer': 'anonymous74100',
        'policy': None,
        'specialization': 'latvie\u0161u valoda',
        'supplemented': [],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'ads',
        'variants': [['Latvian List+EasyList',
                     'https://easylist-downloads.adblockplus.org/latvianlist+easylist.txt'
                     , True], ['Latvian List',
                     'https://raw.githubusercontent.com/Latvian-List/adblock-latvian/master/lists/latvian-list.txt'
                     , False]],
        },
    'Liste FR': {
        'blog': None,
        'changelog': 'https://github.com/easylist/listefr/commits/master',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://forums.lanik.us/viewforum.php?f=91',
        'homepage': 'https://forums.lanik.us/viewforum.php?f=91',
        'maintainer': 'smed79',
        'policy': 'https://forums.lanik.us/viewtopic.php?f=91&t=2837',
        'specialization': 'fran\xe7ais',
        'supplemented': ['Liste AR'],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'ads',
        'variants': [['Liste FR+EasyList',
                     'https://easylist-downloads.adblockplus.org/liste_fr+easylist.txt'
                     , True], ['Liste FR',
                     'https://easylist-downloads.adblockplus.org/liste_fr.txt'
                     , False]],
        },
    'Liste AR': {
        'blog': None,
        'changelog': 'https://github.com/easylist/listear/commits/master',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://forums.lanik.us/viewforum.php?f=98',
        'homepage': 'https://code.google.com/p/liste-ar-adblock/',
        'maintainer': 'smed79',
        'policy': None,
        'specialization': '\u0627\u0644\u0639\u0631\u0628\u064a\u0629',
        'supplemented': [],
        'supplements': ['EasyList', 'Liste FR'],
        'supplementsType': ['ads'],
        'type': 'ads',
        'variants': [['Liste AR+Liste FR+EasyList',
                     'https://easylist-downloads.adblockplus.org/liste_ar+liste_fr+easylist.txt'
                     , True], ['Liste AR',
                     'https://easylist-downloads.adblockplus.org/Liste_AR.txt'
                     , False]],
        },
    'NoCoin': {
        'blog': None,
        'changelog': 'https://github.com/hoshsadiq/adblock-nocoin-list/commits/master/nocoin.txt',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://github.com/hoshsadiq/adblock-nocoin-list/issues',
        'homepage': 'https://github.com/hoshsadiq/adblock-nocoin-list/',
        'maintainer': 'Hosh',
        'policy': None,
        'specialization': 'filters browser based miners such as coin-hive',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': 'other',
        'variants': [['NoCoin',
                     'https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt'
                     , False]],
        },
    "Peter Lowe's list": {
        'blog': None,
        'changelog': 'https://pgl.yoyo.org/adservers/rss/adservers.rss',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': 'https://pgl.yoyo.org/adservers/',
        'maintainer': 'Peter Lowe',
        'policy': 'https://pgl.yoyo.org/adservers/policy.php',
        'specialization': 'English',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': 'ads',
        'variants': [["Peter Lowe's list",
                     'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&mimetype=plaintext'
                     , False]],
        },
    'ROList': {
        'blog': None,
        'changelog': None,
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': 'https://zoso.ro/rolist/',
        'maintainer': 'MenetZ, Zoso',
        'policy': None,
        'specialization': 'rom\xe2nesc',
        'supplemented': [],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'ads',
        'variants': [['ROList+EasyList',
                     'https://easylist-downloads.adblockplus.org/rolist+easylist.txt'
                     , True], ['ROList',
                     'https://www.zoso.ro/pages/rolist.txt', False]],
        },
    'RU AdList': {
        'blog': None,
        'changelog': 'https://github.com/easylist/ruadlist/commits/master/advblock',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://forums.lanik.us/viewforum.php?f=102',
        'homepage': 'https://forums.lanik.us/viewforum.php?f=102',
        'maintainer': 'Lain_13, dimisa',
        'policy': None,
        'specialization': '\u0440\u0443\u0441\u0441\u043a\u0438\u0439, \u0443\u043a\u0440\u0430\u0457\u043d\u0441\u044c\u043a\u0430, \u004f\u02bb\u007a\u0062\u0065\u006b\u0063\u0068\u0061, \u049b\u0430\u0437\u0430\u049b\u0448\u0430',
        'supplemented': [],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'ads',
        'variants': [['RuAdList+EasyList',
                     'https://easylist-downloads.adblockplus.org/ruadlist+easylist.txt'
                     , True], ['RU AdList',
                     'https://easylist-downloads.adblockplus.org/advblock.txt'
                     , False]],
        },
    'Raajje Adlist': {
        'blog': None,
        'changelog': 'https://github.com/evenxzero/Raajje-AdList/commits/master/filter.txt',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': 'https://github.com/evenxzero/Raajje-AdList',
        'maintainer': 'evenxzero',
        'policy': None,
        'specialization': 'Dhivehi',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': 'ads',
        'variants': [['Raajje Adlist',
                     'https://raw.githubusercontent.com/evenxzero/Raajje-AdList/master/filter.txt'
                     , False]],
        },
    'Spam404': {
        'blog': None,
        'changelog': None,
        'contact': 'https://www.spam404.com/domain-blacklist.html',
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': 'https://www.spam404.com/',
        'maintainer': 'Cameron Dawe',
        'policy': None,
        'specialization': 'blocks scam sites',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': 'malware',
        'variants': [['Spam404',
                     'https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt'
                     , False]],
        },
    'Turkish Filters': {
        'blog': None,
        'changelog': 'https://gitlab.com/eyeo/filterlists/turkishfilters/-/commits/main/',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://gitlab.com/eyeo/filterlists/turkishfilters/-/issues',
        'homepage': 'https://gitlab.com/eyeo/filterlists/turkishfilters',
        'maintainer': 'eyeo GmbH',
        'policy': None,
        'specialization': '\u0054\u00fc\u0072\u006b\u00e7\u0065',
        'supplemented': [],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'ads',
        'variants': [['Turkish Filters+EasyList',
                     'https://easylist-downloads.adblockplus.org/turkish-filters+easylist.txt'
                     , True], ['Turkish Filters',
                     'https://easylist-downloads.adblockplus.org/turkish-filters.txt'
                     , False]],
        },
    'Xfiles': {
        'blog': 'https://gioxx.org/tag/abpxfiles/',
        'changelog': 'https://github.com/gioxx/xfiles/commits/master/filtri.txt',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://forum.mozillaitalia.org/',
        'homepage': 'https://xfiles.noads.it/',
        'maintainer': 'Gioxx',
        'policy': None,
        'specialization': 'italiano',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': 'ads',
        'variants': [['Xfiles',
                     'https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt'
                     , False]],
        },
    'YousList': {
        'blog': None,
        'changelog': 'https://github.com/yous/YousList/commits/master/youslist.txt',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://github.com/yous/YousList/issues',
        'homepage': 'https://github.com/yous/YousList',
        'maintainer': 'yous',
        'policy': None,
        'specialization': '\ud55c\uad6d\uc5b4',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': 'ads',
        'variants': [['YousList',
                     'https://raw.githubusercontent.com/yous/YousList/master/youslist.txt'
                     , False]],
        },
    'Tiswagos Liri AdBlockList': {
        'blog': None,
        'changelog': 'https://github.com/Xaival/AdBlockList/commits/main/Adblock_list.txt',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://github.com/Xaival/AdBlockList/issues',
        'homepage': 'https://github.com/Xaival/AdBlockList',
        'maintainer': 'Xaival',
        'policy': None,
        'specialization': 'espa\xf1ol',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': 'ads',
        'variants': [['Tiswagos Liri AdBlockList',
                     'https://raw.githubusercontent.com/Xaival/AdBlockList/main/Adblock_list.txt'
                     , False]],
        },
    'hufilter': {
        'blog': None,
        'changelog': 'https://github.com/hufilter/hufilter/commits/master/hufilter.txt',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': 'https://github.com/hufilter/hufilter/issues',
        'homepage': 'https://github.com/hufilter/hufilter/wiki',
        'maintainer': 'Hufilter contributors',
        'policy': None,
        'specialization': 'magyar',
        'supplemented': [],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'ads',
        'variants': [['hufilter+EasyList',
                     'https://easylist-downloads.adblockplus.org/hufilter+easylist.txt'
                     , True], ['hufilter',
                     'https://raw.githubusercontent.com/hufilter/hufilter/master/hufilter.txt'
                     , False]],
        },
    'void.gr': {
        'blog': None,
        'changelog': None,
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': 'https://www.void.gr/kargig/blog/greek-adblock-plus-filter/',
        'maintainer': None,
        'policy': None,
        'specialization': '\u03b5\u03bb\u03bb\u03b7\u03bd\u03b9\u03ba\u03ac',
        'supplemented': [],
        'supplements': ['EasyList'],
        'supplementsType': ['ads'],
        'type': 'ads',
        'variants': [['void.gr',
                     'https://www.void.gr/kargig/void-gr-filters.txt',
                     False]],
        },
    }

			
