subscriptions = {
    'order': [
        'EasyList',
        'ABPindo',
        'ABPVN List',
        'Bulgarian list',
        "Dandelion Sprout's Nordic Filters",
        'EasyList China',
        'EasyList Czech and Slovak',
        'EasyList Dutch',
        'EasyList Germany',
        'EasyList Hebrew',
        'EasyList Italy',
        'EasyList Lithuania',
        'EasyList Polish',
        'EasyList Portuguese',
        'EasyList Spanish',
        'IndianList',
        'KoreanList',
        'Latvian List',
        'Liste AR',
        'Liste FR',
        'ROList',
        'RU AdList',
        '280blocker for japanese mobile site',
        'ABP Japanese Filters',
        'AdBlockFarsi',
        "CJX's Annoyance List",
        'Colombian filters by yecarrillo',
        'Eesti saitidele kohandatud filter',
        'Estonian filters by Gurud.ee',
        'Filtros Nauscopicos',
        'hufilter',
        'Icelandic ABP List',
        "Peter Lowe's list",
        'Raajje Adlist',
        'Schacks Adblock Plus liste',
         'Tiswagos Liri AdBlockList',
        'void.gr',
        'Xfiles',
        'YousList',
        'Adblock Warning Removal List',
        'ABP filters',
        "I don't care about cookies",
        'EasyList Cookie List',
        'Spam404',
        "Fanboy's Notifications Blocking List",
        'CPBL Filters for Adblock Plus',
        "Fanboy's Annoyances",
        'NoCoin',
        'EasyPrivacy',
        "Fanboy's Social Blocking List",
        ],
    '280blocker for japanese mobile site': {
        'blog': None,
        'changelog': None,
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': u'https://280blocker.net/',
        'maintainer': u'280',
        'policy': None,
        'specialization': u'\u65e5\u672c\u8a9e',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': u'ads',
        'variants': [['280blocker for japanese mobile site',
                     u'https://280blocker.net/files/280blocker_adblock.txt'
                     , False]],
        },
    'ABP Japanese Filters': {
        'blog': u'http://d.hatena.ne.jp/k2jp/',
        'changelog': u'https://github.com/k2jp/abp-japanese-filters/commits/master/abpjf.txt',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://groups.google.com/group/adblock-plus-japanese-filter',
        'homepage': u'https://github.com/k2jp/abp-japanese-filters/',
        'maintainer': u'k2japan',
        'policy': None,
        'specialization': u'\u65e5\u672c\u8a9e',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': u'ads',
        'variants': [['ABP Japanese Filters', u'https://bit.ly/11QrCfx'
                     , False]],
        },
    'ABP filters': {
        'blog': None,
        'changelog': u'https://github.com/abp-filters/abp-filters-anti-cv/commits/master',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://github.com/abp-filters/abp-filters-anti-cv/issues',
        'homepage': u'https://github.com/abp-filters/abp-filters-anti-cv',
        'maintainer': u'eyeo GmbH',
        'policy': None,
        'specialization': u'Removes circumvention ads in Adblock Plus',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': u'circumvention',
        'variants': [['ABP filters',
                     u'https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt'
                     , False]],
        },
    'ABPVN List': {
        'blog': None,
        'changelog': u'https://github.com/abpvn/abpvn/commits/master/filter/abpvn.txt',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'http://www.vn-zoom.com/f77/abp-bo-loc-quang-cao-cho-nguoi-viet-2856275.html',
        'homepage': u'http://abpvn.com/',
        'maintainer': u'Ho\xe0ng Rio',
        'policy': None,
        'specialization': u'Ti\u1ebfng Vi\u1ec7t',
        'supplemented': [],
        'supplements': [u'EasyList'],
        'supplementsType': [u'ads'],
        'type': u'ads',
        'variants': [[u'ABPVN List+EasyList',
                     u'https://easylist-downloads.adblockplus.org/abpvn+easylist.txt'
                     , True], ['ABPVN List',
                     u'https://raw.githubusercontent.com/abpvn/abpvn/master/filter/abpvn.txt'
                     , False]],
        },
    'ABPindo': {
        'blog': None,
        'changelog': None,
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://forums.lanik.us/viewforum.php?f=94',
        'homepage': u'http://abpindo.blogspot.com/',
        'maintainer': u'heradhis',
        'policy': None,
        'specialization': u'Bahasa Indonesia, Melayu',
        'supplemented': [],
        'supplements': [u'EasyList'],
        'supplementsType': [u'ads'],
        'type': u'ads',
        'variants': [[u'ABPindo+EasyList',
                     u'https://easylist-downloads.adblockplus.org/abpindo+easylist.txt'
                     , True], ['ABPindo',
                     u'https://raw.githubusercontent.com/ABPindo/indonesianadblockrules/master/subscriptions/abpindo.txt'
                     , False]],
        },
    'AdBlockFarsi': {
        'blog': None,
        'changelog': u'https://github.com/SlashArash/adblockfa/commits/master/adblockfa.txt',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://github.com/SlashArash/adblockfa/issues',
        'homepage': u'https://github.com/SlashArash/adblockfa',
        'maintainer': u'Arash Kadkhodaei',
        'policy': None,
        'specialization': u'\u0641\u0627\u0631\u0633\u06cc',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': u'ads',
        'variants': [['AdBlockFarsi',
                     u'https://raw.githubusercontent.com/SlashArash/adblockfa/master/adblockfa.txt'
                     , False]],
        },
    'Adblock Warning Removal List': {
        'blog': None,
        'changelog': None,
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': u'https://easylist.to/',
        'maintainer': u'authors of recommended filter lists',
        'policy': None,
        'specialization': u'removes anti-adblock warnings and other obtrusive messages',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': u'anti-adblock',
        'variants': [['Adblock Warning Removal List',
                     u'https://easylist-downloads.adblockplus.org/antiadblockfilters.txt'
                     , False]],
        },
    'Bulgarian list': {
        'blog': None,
        'changelog': u'https://twitter.com/adblockbg',
        'contact': u'https://stanev.org/abp/?SendFilters',
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': u'https://stanev.org/abp/',
        'maintainer': u'\u0410\u043b\u0435\u043a\u0441\u0430\u043d\u0434\u044a\u0440 \u0421\u0442\u0430\u043d\u0435\u0432',
        'policy': None,
        'specialization': u'\u0431\u044a\u043b\u0433\u0430\u0440\u0441\u043a\u0438',
        'supplemented': [],
        'supplements': [u'EasyList'],
        'supplementsType': [u'ads'],
        'type': u'ads',
        'variants': [[u'Bulgarian list+EasyList',
                     u'https://easylist-downloads.adblockplus.org/bulgarian_list+easylist.txt'
                     , True], ['Bulgarian list',
                     u'https://stanev.org/abp/adblock_bg.txt', False]],
        },
    "CJX's Annoyance List": {
        'blog': None,
        'changelog': None,
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': u'http://abpchina.org/forum/forum.php?mod=viewthread&tid=29667',
        'maintainer': u'John',
        'policy': None,
        'specialization': u'removes self-promotion and privacy protection, \u4e2d\u6587',
        'supplemented': [],
        'supplements': [u'EasyList China'],
        'supplementsType': [u'ads'],
        'type': u'ads',
        'variants': [["CJX's Annoyance List",
                     u'https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt'
                     , False]],
        },
    'CPBL Filters for Adblock Plus': {
        'blog': None,
        'changelog': u'https://github.com/bongochong/CombinedPrivacyBlockLists/commits/master/cpbl-abp-list.txt',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://git.io/JTTL0',
        'homepage': u'https://git.io/JTTLB',
        'maintainer': u'Bongochong',
        'policy': None,
        'specialization': u'removes ads, trackers/telemetry, malware and scams',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': u'other',
        'variants': [['CPBL Filters for Adblock Plus',
                     u'https://raw.githubusercontent.com/bongochong/CombinedPrivacyBlockLists/master/cpbl-abp-list.txt'
                     , False]],
        },
    'Colombian filters by yecarrillo': {
        'blog': None,
        'changelog': u'https://github.com/yecarrillo/adblock-colombia/commits/master/adblock_co.txt',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://www.laneros.com/temas/adblockers-y-lista-de-filtros-de-publicidad-para-colombia.230398/',
        'homepage': u'https://github.com/yecarrillo/adblock-colombia',
        'maintainer': u'Yezid Carrillo',
        'policy': None,
        'specialization': u'espa\xf1ol',
        'supplemented': [],
        'supplements': [u'EasyList'],
        'supplementsType': [u'ads'],
        'type': u'ads',
        'variants': [['Colombian filters by yecarrillo',
                     u'https://raw.githubusercontent.com/yecarrillo/adblock-colombia/master/adblock_co.txt'
                     , False]],
        },
    "Dandelion Sprout's Nordic Filters": {
        'blog': None,
        'changelog': u'https://github.com/DandelionSprout/adfilt/commits/master/NorwegianExperimentalList%20alternate%20versions/NordicFiltersABP-Inclusion.txt',
        'contact': u'https://github.com/DandelionSprout/adfilt/issues',
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': u'https://github.com/DandelionSprout/adfilt',
        'maintainer': u'Imre Kristoffer Eilertsen',
        'policy': None,
        'specialization': u'norsk, norsk, norsk, dansk, \xedslenska, f\xf8royskt, kalaallisut',
        'supplemented': [],
        'supplements': [u'EasyList'],
        'supplementsType': [u'ads'],
        'type': u'ads',
        'variants': [[u"Dandelion Sprout's Nordic Filters+EasyList",
                     u'https://easylist-downloads.adblockplus.org/dandelion_sprouts_nordic_filters+easylist.txt'
                     , True], ["Dandelion Sprout's Nordic Filters",
                     u'https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianExperimentalList%20alternate%20versions/NordicFiltersABP-Inclusion.txt'
                     , False]],
        },
    'EasyList': {
        'blog': u'https://easylist.to/category/articles.html',
        'changelog': u'https://github.com/easylist/easylist/commits/master',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://forums.lanik.us/',
        'homepage': u'https://easylist.to/',
        'maintainer': u'fanboy, MonztA, Famlam, Khrin',
        'policy': u'https://easylist.to/pages/policy.html',
        'specialization': u'English',
        'supplemented': [
            'ABPindo',
            'ABPVN List',
            'Bulgarian list',
            "Dandelion Sprout's Nordic Filters",
            'EasyList China',
            'EasyList Czech and Slovak',
            'EasyList Dutch',
            'EasyList Germany',
            'EasyList Hebrew',
            'EasyList Italy',
            'EasyList Lithuania',
            'EasyList Polish',
            'EasyList Portuguese',
            'EasyList Spanish',
            'IndianList',
            'KoreanList',
            'Latvian List',
            'Liste AR',
            'Liste FR',
            'ROList',
            'RU AdList',
            'Colombian filters by yecarrillo',
            'Icelandic ABP List',
            'void.gr',
            ],
        'supplements': [],
        'supplementsType': [],
        'type': u'ads',
        'variants': [['EasyList',
                     u'https://easylist-downloads.adblockplus.org/easylist.txt'
                     , False]],
        },
    'EasyList China': {
        'blog': None,
        'changelog': u'https://github.com/easylist/easylistchina/commits/master',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': u'https://github.com/easylist/easylistchina',
        'maintainer': u'John, Li',
        'policy': None,
        'specialization': u'\u4e2d\u6587',
        'supplemented': ["CJX's Annoyance List"],
        'supplements': [u'EasyList'],
        'supplementsType': [u'ads'],
        'type': u'ads',
        'variants': [[u'EasyList China+EasyList',
                     u'https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt'
                     , True], ['EasyList China',
                     u'https://easylist-downloads.adblockplus.org/easylistchina.txt'
                     , False]],
        },
    'EasyList Cookie List': {
        'blog': None,
        'changelog': u'https://github.com/easylist/easylist/commits/master/easylist_cookie',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://forums.lanik.us/',
        'homepage': u'https://easylist.to/',
        'maintainer': u'fanboy, Khrin, MonztA',
        'policy': None,
        'specialization': u'cookies banners, GDPR overlay windows and other privacy-related notices',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': u'cookies',
        'variants': [['EasyList Cookie List',
                     u'https://easylist-downloads.adblockplus.org/easylist-cookie.txt'
                     , False]],
        },
    'EasyList Czech and Slovak': {
        'blog': None,
        'changelog': u'https://github.com/tomasko126/easylistczechandslovak/commits/master/filters.txt',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://easylist-czech-and-slovak.tenderapp.com/',
        'homepage': u'https://adblock.sk/',
        'maintainer': u'tomasko126',
        'policy': None,
        'specialization': u'\u010de\u0161tina, sloven\u010dina',
        'supplemented': [],
        'supplements': [u'EasyList'],
        'supplementsType': [u'ads'],
        'type': u'ads',
        'variants': [[u'EasyList Czech and Slovak+EasyList',
                     u'https://easylist-downloads.adblockplus.org/easylistczechslovak+easylist.txt'
                     , True], ['EasyList Czech and Slovak',
                     u'https://raw.github.com/tomasko126/easylistczechandslovak/master/filters.txt'
                     , False]],
        },
    'EasyList Dutch': {
        'blog': None,
        'changelog': u'https://hg.adblockplus.org/easylistdutch/',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://forums.lanik.us/viewforum.php?f=100',
        'homepage': u'https://easylist.to/',
        'maintainer': u'Famlam',
        'policy': None,
        'specialization': u'Nederlands',
        'supplemented': [],
        'supplements': [u'EasyList'],
        'supplementsType': [u'ads'],
        'type': u'ads',
        'variants': [[u'EasyList Dutch+EasyList',
                     u'https://easylist-downloads.adblockplus.org/easylistdutch+easylist.txt'
                     , True], ['EasyList Dutch',
                     u'https://easylist-downloads.adblockplus.org/easylistdutch.txt'
                     , False]],
        },
    'EasyList Germany': {
        'blog': None,
        'changelog': u'https://github.com/easylist/easylistgermany/commits/master',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://forums.lanik.us/viewforum.php?f=90',
        'homepage': u'https://easylist.to/',
        'maintainer': u'MonztA, Famlam',
        'policy': u'https://easylist.to/pages/policy.html',
        'specialization': u'Deutsch',
        'supplemented': [],
        'supplements': [u'EasyList'],
        'supplementsType': [u'ads'],
        'type': u'ads',
        'variants': [[u'EasyList Germany+EasyList',
                     u'https://easylist-downloads.adblockplus.org/easylistgermany+easylist.txt'
                     , True], ['EasyList Germany',
                     u'https://easylist-downloads.adblockplus.org/easylistgermany.txt'
                     , False]],
        },
    'EasyList Hebrew': {
        'blog': None,
        'changelog': u'https://github.com/easylist/EasyListHebrew/commits/master/EasyListHebrew.txt',
        'contact': u'https://github.com/easylist/EasyListHebrew/wiki/%D7%93%D7%99%D7%95%D7%95%D7%97-%D7%A2%D7%9C-%D7%A4%D7%A8%D7%A1%D7%95%D7%9E%D7%95%D7%AA-%D7%95%D7%91%D7%A2%D7%99%D7%95%D7%AA-%7C-Reporting-on-ads-and-problems',
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': u'https://github.com/easylist/EasyListHebrew',
        'maintainer': u'BsT',
        'policy': None,
        'specialization': u'\u05e2\u05d1\u05e8\u05d9\u05ea',
        'supplemented': [],
        'supplements': [u'EasyList'],
        'supplementsType': [u'ads'],
        'type': u'ads',
        'variants': [[u'EasyList Hebrew+EasyList',
                     u'https://easylist-downloads.adblockplus.org/israellist+easylist.txt'
                     , True], ['EasyList Hebrew',
                     u'https://raw.githubusercontent.com/easylist/EasyListHebrew/master/EasyListHebrew.txt'
                     , False]],
        },
    'EasyList Italy': {
        'blog': None,
        'changelog': u'https://hg.adblockplus.org/easylistitaly/summary',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://forums.lanik.us/viewforum.php?f=96',
        'homepage': u'https://easylist.to/',
        'maintainer': u'Khrin',
        'policy': u'https://easylist.to/pages/policy.html',
        'specialization': u'italiano',
        'supplemented': [],
        'supplements': [u'EasyList'],
        'supplementsType': [u'ads'],
        'type': u'ads',
        'variants': [[u'EasyList Italy+EasyList',
                     u'https://easylist-downloads.adblockplus.org/easylistitaly+easylist.txt'
                     , True], ['EasyList Italy',
                     u'https://easylist-downloads.adblockplus.org/easylistitaly.txt'
                     , False]],
        },
    'EasyList Lithuania': {
        'blog': None,
        'changelog': u'https://github.com/EasyList-Lithuania/easylist_lithuania/commits/master/easylistlithuania.txt',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://forums.lanik.us/viewforum.php?f=101',
        'homepage': u'http://margevicius.lt/',
        'maintainer': u'Algimantas Margevi\u010dius',
        'policy': None,
        'specialization': u'lietuvi\u0173 kalba',
        'supplemented': [],
        'supplements': [u'EasyList'],
        'supplementsType': [u'ads'],
        'type': u'ads',
        'variants': [[u'EasyList Lithuania+EasyList',
                     u'https://easylist-downloads.adblockplus.org/easylistlithuania+easylist.txt'
                     , True], ['EasyList Lithuania',
                     u'https://raw.githubusercontent.com/EasyList-Lithuania/easylist_lithuania/master/easylistlithuania.txt'
                     , False]],
        },
    'EasyList Polish': {
        'blog': None,
        'changelog': None,
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://forums.lanik.us/viewforum.php?f=107',
        'homepage': u'https://easylist.to/',
        'maintainer': u'krzysiek-gala',
        'policy': u'https://easylist.to/pages/policy.html',
        'specialization': u'polski',
        'supplemented': [],
        'supplements': [u'EasyList'],
        'supplementsType': [u'ads'],
        'type': u'ads',
        'variants': [[u'EasyList Polish+EasyList',
                     u'https://easylist-downloads.adblockplus.org/easylistpolish+easylist.txt'
                     , True], ['EasyList Polish',
                     u'https://easylist-downloads.adblockplus.org/easylistpolish.txt'
                     , False]],
        },
    'EasyList Portuguese': {
        'blog': None,
        'changelog': u'https://github.com/easylist/easylistportuguese/commits/master',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://forums.lanik.us/viewforum.php?f=109',
        'homepage': u'https://easylist.to/',
        'maintainer': u'diaux',
        'policy': u'https://easylist.to/pages/policy.html',
        'specialization': u'portugu\xeas',
        'supplemented': [],
        'supplements': [u'EasyList'],
        'supplementsType': [u'ads'],
        'type': u'ads',
        'variants': [[u'EasyList Portuguese+EasyList',
                     u'https://easylist-downloads.adblockplus.org/easylistportuguese+easylist.txt'
                     , True], ['EasyList Portuguese',
                     u'https://easylist-downloads.adblockplus.org/easylistportuguese.txt'
                     , False]],
        },
    'EasyList Spanish': {
        'blog': None,
        'changelog': u'https://github.com/easylist/easylistspanish/commits/master',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://forums.lanik.us/viewforum.php?f=103',
        'homepage': u'https://easylist.to/',
        'maintainer': u'jabonsolo',
        'policy': u'https://easylist.to/pages/policy.html',
        'specialization': u'espa\xf1ol',
        'supplemented': [],
        'supplements': [u'EasyList'],
        'supplementsType': [u'ads'],
        'type': u'ads',
        'variants': [[u'EasyList Spanish+EasyList',
                     u'https://easylist-downloads.adblockplus.org/easylistspanish+easylist.txt'
                     , True], ['EasyList Spanish',
                     u'https://easylist-downloads.adblockplus.org/easylistspanish.txt'
                     , False]],
        },
    'EasyPrivacy': {
        'blog': u'https://easylist.to/category/articles.html',
        'changelog': u'https://github.com/easylist/easylist/commits/master/easyprivacy',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://forums.lanik.us/',
        'homepage': u'https://easylist.to/',
        'maintainer': u'fanboy, MonztA, Famlam, Khrin',
        'policy': u'https://easylist.to/pages/policy.html',
        'specialization': u'privacy protection',
        'supplemented': [],
        'supplements': [u'EasyList'],
        'supplementsType': [u'ads'],
        'type': u'privacy',
        'variants': [['EasyPrivacy',
                     u'https://easylist-downloads.adblockplus.org/easyprivacy.txt'
                     , False], [u'EasyPrivacy+EasyList',
                     u'https://easylist-downloads.adblockplus.org/easyprivacy+easylist.txt'
                     , True]],
        },
    'Eesti saitidele kohandatud filter': {
        'blog': None,
        'changelog': None,
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': u'https://adblock.ee/',
        'maintainer': u'Sander Lepik',
        'policy': None,
        'specialization': u'Eesti keel',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': u'ads',
        'variants': [['Eesti saitidele kohandatud filter',
                     u'https://adblock.ee/list.php', False]],
        },
    'Estonian filters by Gurud.ee': {
        'blog': None,
        'changelog': None,
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': u'https://gurud.ee/',
        'maintainer': u'Janno Lamus',
        'policy': None,
        'specialization': u'Eesti keel',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': u'ads',
        'variants': [['Estonian filters by Gurud.ee',
                     u'https://gurud.ee/ab.txt', False]],
        },
    "Fanboy's Annoyances": {
        'blog': None,
        'changelog': u'https://github.com/easylist/easylist/commits/master/fanboy-addon',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://forums.lanik.us/',
        'homepage': u'https://easylist.to/',
        'maintainer': u'fanboy',
        'policy': None,
        'specialization': u"removes online annoyances (includes Fanboy's Social Blocking List)",
        'supplemented': [],
        'supplements': [u'EasyList'],
        'supplementsType': [u'ads'],
        'type': u'other',
        'variants': [["Fanboy's Annoyances",
                     u'https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt'
                     , False]],
        },
    "Fanboy's Notifications Blocking List": {
        'blog': None,
        'changelog': u'https://github.com/easylist/easylist/commits/master/fanboy-addon',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://forums.lanik.us/',
        'homepage': u'https://easylist.to/',
        'maintainer': u'fanboy',
        'policy': None,
        'specialization': u"removes website notification popups (included in Fanboy's Annoyances)",
        'supplemented': [],
        'supplements': [u'EasyList'],
        'supplementsType': [u'ads'],
        'type': u'notifications',
        'variants': [["Fanboy's Notifications Blocking List",
                     u'https://easylist-downloads.adblockplus.org/fanboy-notifications.txt'
                     , False]],
        },
    "Fanboy's Social Blocking List": {
        'blog': None,
        'changelog': u'https://github.com/easylist/easylist/commits/master/fanboy-addon',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'http://forums.lanik.us/',
        'homepage': u'https://easylist.to/',
        'maintainer': u'fanboy, Famlam, MonztA',
        'policy': None,
        'specialization': u'removes social media integration',
        'supplemented': [],
        'supplements': [u'EasyList'],
        'supplementsType': [u'ads'],
        'type': u'social',
        'variants': [["Fanboy's Social Blocking List",
                     u'https://easylist-downloads.adblockplus.org/fanboy-social.txt'
                     , False]],
        },
    'Filtros Nauscopicos': {
        'blog': None,
        'changelog': None,
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': u'http://nauscopio.nireblog.com/cat/filtrado',
        'maintainer': u'maty',
        'policy': None,
        'specialization': u'espa\xf1ol',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': u'ads',
        'variants': [['Filtros Nauscopicos',
                     u'http://abp.mozilla-hispano.org/nauscopio/filtros.txt'
                     , False]],
        },
    "I don't care about cookies": {
        'blog': None,
        'changelog': None,
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': u'https://www.i-dont-care-about-cookies.eu/',
        'maintainer': u'Daniel Kladnik',
        'policy': None,
        'specialization': u'filters obtrusive EU cookie law notices',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': u'cookies',
        'variants': [["I don't care about cookies",
                     u'https://easylist-downloads.adblockplus.org/i_dont_care_about_cookies.txt'
                     , False]],
        },
    'Icelandic ABP List': {
        'blog': None,
        'changelog': None,
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': u'https://adblock.gardar.net/',
        'maintainer': u'Gar\xf0ar',
        'policy': None,
        'specialization': u'\xedslenska',
        'supplemented': [],
        'supplements': [u'EasyList'],
        'supplementsType': [u'ads'],
        'type': u'ads',
        'variants': [['Icelandic ABP List',
                     u'https://adblock.gardar.net/is.abp.txt', False]],
        },
    'IndianList': {
        'blog': None,
        'changelog': u'https://github.com/mediumkreation/IndianList/commits/master/IndianList',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://forums.lanik.us/viewforum.php?f=110',
        'homepage': u'https://easylist.to/',
        'maintainer': u'mediumkreation',
        'policy': u'https://easylist.to/pages/policy.html',
        'specialization': u'\u09ac\u09be\u0982\u09b2\u09be (\u09ad\u09be\u09b0\u09a4), \u0a97\u0ac1\u0a9c\u0ab0\u0abe\u0aa4\u0ac0 (\u0aad\u0abe\u0ab0\u0aa4), \u092d\u093e\u0930\u0924\u0940\u092f, \u0a2a\u0a70\u0a1c\u0a3e\u0a2c\u0a40 (\u0a2d\u0a3e\u0a30\u0a24), \u0985\u09b8\u09ae\u09c0\u09af\u09bc\u09be, \u092e\u0930\u093e\u0920\u0940, \u0d2e\u0d32\u0d2f\u0d3e\u0d33\u0d02, \u0c24\u0c46\u0c32\u0c41\u0c17\u0c41, \u0c95\u0ca8\u0ccd\u0ca8\u0ca1, \u0b13\u0b21\u0b3c\u0b3f\u0b06, \u0928\u0947\u092a\u093e\u0932\u0940, \u0dc3\u0dd2\u0d82\u0dc4\u0dbd',
        'supplemented': [],
        'supplements': [u'EasyList'],
        'supplementsType': [u'ads'],
        'type': u'ads',
        'variants': [[u'IndianList+EasyList',
                     u'https://easylist-downloads.adblockplus.org/indianlist+easylist.txt'
                     , True], ['IndianList',
                     u'https://easylist-downloads.adblockplus.org/indianlist.txt'
                     , False]],
        },
    'KoreanList': {
        'blog': None,
        'changelog': u'https://github.com/easylist/KoreanList/commits/master/KoreanList',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://forums.lanik.us/viewforum.php?f=111',
        'homepage': u'https://easylist.to/',
        'maintainer': u'Mark Choi',
        'policy': u'https://easylist.to/pages/policy.html',
        'specialization': u'\ud55c\uad6d\uc5b4',
        'supplemented': [],
        'supplements': [u'EasyList'],
        'supplementsType': [u'ads'],
        'type': u'ads',
        'variants': [[u'KoreanList+EasyList',
                     u'https://easylist-downloads.adblockplus.org/koreanlist+easylist.txt'
                     , True], ['KoreanList',
                     u'https://easylist-downloads.adblockplus.org/koreanlist.txt'
                     , False]],
        },
    'Latvian List': {
        'blog': None,
        'changelog': u'https://notabug.org/latvian-list/adblock-latvian/commits/master/lists/latvian-list.txt',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://forums.lanik.us/viewforum.php?f=99',
        'homepage': u'https://notabug.org/latvian-list/adblock-latvian',
        'maintainer': u'anonymous74100',
        'policy': None,
        'specialization': u'latvie\u0161u valoda',
        'supplemented': [],
        'supplements': [u'EasyList'],
        'supplementsType': [u'ads'],
        'type': u'ads',
        'variants': [[u'Latvian List+EasyList',
                     u'https://easylist-downloads.adblockplus.org/latvianlist+easylist.txt'
                     , True], ['Latvian List',
                     u'https://notabug.org/latvian-list/adblock-latvian/raw/master/lists/latvian-list.txt'
                     , False]],
        },
    'Liste AR': {
        'blog': None,
        'changelog': u'https://hg.adblockplus.org/listear/',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://forums.lanik.us/viewforum.php?f=98',
        'homepage': u'https://code.google.com/p/liste-ar-adblock/',
        'maintainer': u'smed79',
        'policy': None,
        'specialization': u'\u0627\u0644\u0639\u0631\u0628\u064a\u0629',
        'supplemented': [],
        'supplements': [u'EasyList'],
        'supplementsType': [u'ads'],
        'type': u'ads',
        'variants': [[u'Liste AR+Liste FR+EasyList',
                     u'https://easylist-downloads.adblockplus.org/liste_ar+liste_fr+easylist.txt'
                     , True], ['Liste AR',
                     u'https://easylist-downloads.adblockplus.org/Liste_AR.txt'
                     , False]],
        },
    'Liste FR': {
        'blog': None,
        'changelog': u'https://hg.adblockplus.org/listefr/',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://forums.lanik.us/viewforum.php?f=91',
        'homepage': u'https://forums.lanik.us/viewforum.php?f=91',
        'maintainer': u'Lian, Crits, smed79',
        'policy': u'https://forums.lanik.us/viewtopic.php?f=91&t=2837',
        'specialization': u'fran\xe7ais',
        'supplemented': [],
        'supplements': [u'EasyList'],
        'supplementsType': [u'ads'],
        'type': u'ads',
        'variants': [[u'Liste FR+EasyList',
                     u'https://easylist-downloads.adblockplus.org/liste_fr+easylist.txt'
                     , True], ['Liste FR',
                     u'https://easylist-downloads.adblockplus.org/liste_fr.txt'
                     , False]],
        },
    'NoCoin': {
        'blog': None,
        'changelog': u'https://github.com/hoshsadiq/adblock-nocoin-list/commits/master/nocoin.txt',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://github.com/hoshsadiq/adblock-nocoin-list/issues',
        'homepage': u'https://github.com/hoshsadiq/adblock-nocoin-list/',
        'maintainer': u'Hosh',
        'policy': None,
        'specialization': u'filters browser based miners such as coin-hive',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': u'other',
        'variants': [['NoCoin',
                     u'https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt'
                     , False]],
        },
    "Peter Lowe's list": {
        'blog': None,
        'changelog': u'https://pgl.yoyo.org/adservers/rss/adservers.rss',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': u'https://pgl.yoyo.org/adservers/',
        'maintainer': u'Peter Lowe',
        'policy': u'https://pgl.yoyo.org/adservers/policy.php',
        'specialization': u'English',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': u'ads',
        'variants': [["Peter Lowe's list",
                     u'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&mimetype=plaintext'
                     , False]],
        },
    'ROList': {
        'blog': None,
        'changelog': None,
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': u'https://zoso.ro/rolist/',
        'maintainer': u'MenetZ, Zoso',
        'policy': None,
        'specialization': u'rom\xe2nesc',
        'supplemented': [],
        'supplements': [u'EasyList'],
        'supplementsType': [u'ads'],
        'type': u'ads',
        'variants': [[u'ROList+EasyList',
                     u'https://easylist-downloads.adblockplus.org/rolist+easylist.txt'
                     , True], ['ROList',
                     u'https://www.zoso.ro/pages/rolist.txt', False]],
        },
    'RU AdList': {
        'blog': None,
        'changelog': u'https://hg.adblockplus.org/ruadlist/',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://forums.lanik.us/viewforum.php?f=102',
        'homepage': u'https://forums.lanik.us/viewforum.php?f=102',
        'maintainer': u'Lain_13, dimisa',
        'policy': None,
        'specialization': u'\u0440\u0443\u0441\u0441\u043a\u0438\u0439, \u0443\u043a\u0440\u0430\u0457\u043d\u0441\u044c\u043a\u0430',
        'supplemented': [],
        'supplements': [u'EasyList'],
        'supplementsType': [u'ads'],
        'type': u'ads',
        'variants': [[u'RuAdList+EasyList',
                     u'https://easylist-downloads.adblockplus.org/ruadlist+easylist.txt'
                     , True], ['RU AdList',
                     u'https://easylist-downloads.adblockplus.org/advblock.txt'
                     , False]],
        },
    'Raajje Adlist': {
        'blog': None,
        'changelog': u'https://github.com/evenxzero/Raajje-AdList/commits/master/filter.txt',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': u'https://github.com/evenxzero/Raajje-AdList',
        'maintainer': u'evenxzero',
        'policy': None,
        'specialization': u'Dhivehi',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': u'ads',
        'variants': [['Raajje Adlist',
                     u'https://raw.githubusercontent.com/evenxzero/Raajje-AdList/master/filter.txt'
                     , False]],
        },
    'Schacks Adblock Plus liste': {
        'blog': None,
        'changelog': None,
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': u'https://henrik.schack.dk/adblock/',
        'maintainer': u'Henrik Schacks',
        'policy': None,
        'specialization': u'dansk',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': u'ads',
        'variants': [['Schacks Adblock Plus liste',
                     u'https://adblock.dk/block.csv', False]],
        },
    'Spam404': {
        'blog': None,
        'changelog': None,
        'contact': u'https://www.spam404.com/domain-blacklist.html',
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': u'https://www.spam404.com/',
        'maintainer': u'Cameron Dawe',
        'policy': None,
        'specialization': u'blocks scam sites',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': u'malware',
        'variants': [['Spam404',
                     u'https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt'
                     , False]],
        },
    'Xfiles': {
        'blog': u'https://gioxx.org/tag/abpxfiles/',
        'changelog': u'https://github.com/gioxx/xfiles/commits/master/filtri.txt',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://forum.mozillaitalia.org/',
        'homepage': u'https://xfiles.noads.it/',
        'maintainer': u'Gioxx',
        'policy': None,
        'specialization': u'italiano',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': u'ads',
        'variants': [['Xfiles',
                     u'https://raw.githubusercontent.com/gioxx/xfiles/master/filtri.txt'
                     , False]],
        },
    'YousList': {
        'blog': None,
        'changelog': u'https://github.com/yous/YousList/commits/master/youslist.txt',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://github.com/yous/YousList/issues',
        'homepage': u'https://github.com/yous/YousList',
        'maintainer': u'yous',
        'policy': None,
        'specialization': u'\ud55c\uad6d\uc5b4',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': u'ads',
        'variants': [['YousList',
                     u'https://raw.githubusercontent.com/yous/YousList/master/youslist.txt'
                     , False]],
        },
    'Tiswagos Liri AdBlockList': {
        'blog': None,
        'changelog': u'https://github.com/Xaival/AdBlockList/commits/main/Adblock_list.txt',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://github.com/Xaival/AdBlockList/issues',
        'homepage': u'https://github.com/Xaival/AdBlockList',
        'maintainer': u'Xaival',
        'policy': None,
        'specialization': u'espa\xf1ol',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': u'ads',
        'variants': [['Tiswagos Liri AdBlockList',
                     u'https://raw.githubusercontent.com/Xaival/AdBlockList/main/Adblock_list.txt'
                     , False]],
        },
    'hufilter': {
        'blog': None,
        'changelog': u'https://github.com/hufilter/hufilter/commits/master/hufilter-abp.txt',
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': u'https://github.com/hufilter/hufilter/issues',
        'homepage': u'https://github.com/hufilter/hufilter/wiki',
        'maintainer': u'Hufilter contributors',
        'policy': None,
        'specialization': u'magyar',
        'supplemented': [],
        'supplements': [],
        'supplementsType': [],
        'type': u'ads',
        'variants': [['hufilter',
                     u'https://raw.githubusercontent.com/hufilter/hufilter/master/hufilter-abp.txt'
                     , False]],
        },
    'void.gr': {
        'blog': None,
        'changelog': None,
        'contact': None,
        'deprecated': False,
        'faq': None,
        'forum': None,
        'homepage': u'https://www.void.gr/kargig/blog/greek-adblock-plus-filter/',
        'maintainer': None,
        'policy': None,
        'specialization': u'\u03b5\u03bb\u03bb\u03b7\u03bd\u03b9\u03ba\u03ac',
        'supplemented': [],
        'supplements': [u'EasyList'],
        'supplementsType': [u'ads'],
        'type': u'ads',
        'variants': [['void.gr',
                     u'https://www.void.gr/kargig/void-gr-filters.txt',
                     False]],
        },
    }

			
